In [1]:
import numpy as np

In [165]:
a = np.array([0.3, 0.35])
prednum = 2
patch = 3
N0 = 10
P0 = 5
c = np.array([0.4,0.4])
m1 = 0.1
m2 = [0.1, 0.1]
w = [1, 2]
k = 10**10
numruns = 5
gens = 1000
mn = -0.1
t = 10**-20
rho = 0.5
std = 0.7

In [66]:
allrand = np.random.randn(patch*numruns*(gens + 1)).reshape(gens+1, patch, numruns)

In [67]:
ipops = np.array([N0]*(patch*numruns)).reshape(patch, numruns)

In [106]:
ippops = np.array([P0]*(patch*numruns*prednum)).reshape(prednum,patch, numruns)

In [69]:
noise = allrand[1,:,:]

In [71]:
rt1 = rho*noise + np.sqrt(1- rho**2)* allrand[i, :, :]

In [171]:
a = a[:, np.newaxis, np.newaxis]

In [167]:
c = c[:, np.newaxis, np.newaxis]
c

array([[[ 0.4]],

       [[ 0.4]]])

In [175]:
inter = a*ippops

In [176]:
inter.sum(axis = 0)

array([[ 3.25,  3.25,  3.25,  3.25,  3.25],
       [ 3.25,  3.25,  3.25,  3.25,  3.25],
       [ 3.25,  3.25,  3.25,  3.25,  3.25]])

In [146]:
newprey = noise*np.exp(ipops/k)*np.exp(-1*inter.sum(axis = 0))

In [168]:
c*ipops*(1-np.exp(-1*inter))

array([[[ 3.10747936,  3.10747936,  3.10747936,  3.10747936,  3.10747936],
        [ 3.10747936,  3.10747936,  3.10747936,  3.10747936,  3.10747936],
        [ 3.10747936,  3.10747936,  3.10747936,  3.10747936,  3.10747936]],

       [[ 3.30490423,  3.30490423,  3.30490423,  3.30490423,  3.30490423],
        [ 3.30490423,  3.30490423,  3.30490423,  3.30490423,  3.30490423],
        [ 3.30490423,  3.30490423,  3.30490423,  3.30490423,  3.30490423]]])

In [169]:
w < w

False