In [1]:
import numpy as np

In [6]:
a = np.array([0.35, 0.35])
prednum = 2
patch = 3
N0 = 10
P0 = 5
c = np.array([0.4, 0.4])
m1 = 0.1
m2 = [0.1, 0.1]
w = [1, 2]
k = 10**10
numruns = 5
gens = 10
mn = -0.1
t = 10**-20
rho = 0.5
std = 0.7

In [7]:
np.random.seed(1)

In [8]:
allrand = np.random.randn(patch*numruns*(gens + 1)).reshape(gens+1, patch, numruns)

In [9]:
ipops = np.array([N0]*(patch*numruns)).reshape(patch, numruns)

In [7]:
ippops = np.array([P0]*(patch*numruns*prednum)).reshape(prednum,patch, numruns)

In [8]:
noise = allrand[1,:,:]

In [10]:
rt1 = rho*noise + np.sqrt(1- rho**2)* allrand[1, :, :]

In [11]:
a = a[:, np.newaxis, np.newaxis]

In [12]:
c = c[:, np.newaxis, np.newaxis]
c

array([[[ 0.4]],

       [[ 0.4]]])

In [13]:
inter = a*ippops

In [14]:
inter.sum(axis = 0)

array([[ 3.25,  3.25,  3.25,  3.25,  3.25],
       [ 3.25,  3.25,  3.25,  3.25,  3.25],
       [ 3.25,  3.25,  3.25,  3.25,  3.25]])

In [15]:
newprey = noise*np.exp(ipops/k)*np.exp(-1*inter.sum(axis = 0))

In [16]:
c*ipops*(1-np.exp(-1*inter))

array([[[ 3.10747936,  3.10747936,  3.10747936,  3.10747936,  3.10747936],
        [ 3.10747936,  3.10747936,  3.10747936,  3.10747936,  3.10747936],
        [ 3.10747936,  3.10747936,  3.10747936,  3.10747936,  3.10747936]],

       [[ 3.30490423,  3.30490423,  3.30490423,  3.30490423,  3.30490423],
        [ 3.30490423,  3.30490423,  3.30490423,  3.30490423,  3.30490423],
        [ 3.30490423,  3.30490423,  3.30490423,  3.30490423,  3.30490423]]])

In [17]:
w < w

False

In [21]:
w[0] < w[1]

True

In [27]:
w < [1,1]

False

In [28]:
iter(w)